# Generated by Django 3.1 on 2021-05-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20210510_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelGlass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_code', models.CharField(max_length=200)),
                ('model_name', models.CharField(max_length=200)),
            ],
        ),
    ]
