# Generated by Django 3.1 on 2021-05-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_modelglass'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelglass',
            name='model_image',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
