# Generated by Django 3.1 on 2021-05-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_modelglass_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelglass',
            name='model_image',
            field=models.ImageField(null=True, upload_to='image/%y', verbose_name=''),
        ),
    ]
