# Generated by Django 3.1 on 2021-05-15 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20210514_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelGlassWithDefect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('model_code', models.CharField(max_length=200)),
                ('model_name', models.CharField(max_length=200)),
                ('model_desc', models.CharField(max_length=200, null=True)),
                ('defect_name', models.CharField(max_length=200)),
                ('date_select', models.DateField()),
                ('shift', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='defect',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='modelglass',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
