# Generated by Django 3.1 on 2021-05-18 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20210517_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelglasswithdefect',
            name='department',
        ),
    ]
