# Generated by Django 3.1 on 2021-05-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_remove_modelglasswithdefect_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelglasswithdefect',
            name='department',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
