# Generated by Django 3.1 on 2021-05-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_modelglasswithdefect_point_defect'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelglasswithdefect',
            name='number_glass',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
