# Generated by Django 3.1 on 2021-05-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_modelglasswithdefect_number_glass'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelglasswithdefect',
            name='status_glass',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
