# Generated by Django 3.1 on 2021-06-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0019_auto_20210605_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelglass',
            name='model_desc',
            field=models.TextField(null=True),
        ),
    ]
