# Generated by Django 3.1 on 2021-06-05 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0020_auto_20210605_1147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='modelGlassWithDefect_for_export',
        ),
    ]
