# Generated by Django 3.1 on 2021-06-05 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0022_auto_20210605_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defect',
            name='defect_name',
        ),
        migrations.RemoveField(
            model_name='modelglass',
            name='model_code',
        ),
        migrations.RemoveField(
            model_name='modelglass',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='modelglasswithdefect',
            name='model_code',
        ),
        migrations.RemoveField(
            model_name='modelglasswithdefect',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='modelglasswithdefect',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='shift',
        ),
    ]
