# Generated by Django 3.1 on 2021-06-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0024_auto_20210605_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='defect_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
