# Generated by Django 3.1 on 2021-06-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0025_defect_defect_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shift',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='defect',
            name='defect_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modelglass',
            name='model_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modelglass',
            name='model_desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modelglass',
            name='model_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modelglasswithdefect',
            name='defect_name1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modelglasswithdefect',
            name='defect_name2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modelglasswithdefect',
            name='defect_name3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modelglasswithdefect',
            name='defect_name4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modelglasswithdefect',
            name='defect_name5',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modelglasswithdefect',
            name='department',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modelglasswithdefect',
            name='model_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modelglasswithdefect',
            name='model_desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modelglasswithdefect',
            name='model_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modelglasswithdefect',
            name='number_glass',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modelglasswithdefect',
            name='point_defect',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modelglasswithdefect',
            name='shift',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modelglasswithdefect',
            name='status_glass',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
