# Generated by Django 3.1 on 2021-06-05 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0026_auto_20210605_1402'),
    ]

    operations = [
        migrations.DeleteModel(
            name='modelGlass',
        ),
        migrations.DeleteModel(
            name='modelGlassWithDefect',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
